import { Weapons } from '@components/statistics/types';
import { WeaponCategories, WeaponDefinition, WeaponQualities, WeaponRpmFormulas } from '@components/weapons/types';

type WeaponMapDefinition = Partial<Omit<WeaponDefinition, 'name' | 'qualities'>> & {
  name: Weapons;
  qualities: Partial<Record<WeaponQualities, number>>;
};

type WeaponsMapDefinition = {
  [key in 'Ranged' | 'Melee']: WeaponMapDefinition[];
};

// All weapons that fire in bursts, shot 3 times (Beretta M9 / M16)
export const burstCount = 3;

// Map each weapon to their matching line (per quality) from data document
export const WeaponsMap: WeaponsMapDefinition = {
  Ranged: [
    // AR
    {
      name: Weapons.M4Carbine,
      category: WeaponCategories.AssaultRifle,
      image: 'm4.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 6,
        [WeaponQualities.Uncommon]: 7,
        [WeaponQualities.Rare]: 8,
        [WeaponQualities.Epic]: 9,
      },
    },
    {
      name: Weapons.Pestilence,
      category: WeaponCategories.AssaultRifle,
      image: 'pestilence.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: false,
        magazine: false,
        scope: false,
        stock: false,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.LegendaryWeak]: 10,
        [WeaponQualities.Legendary]: 11,
      },
      notes: {
        'Atrophy': 'Successful hits with this weapon apply a stacking 3 damage per second and reduces the damage the target deals by 1%.',
      },
    },
    {
      name: Weapons.AK47,
      category: WeaponCategories.AssaultRifle,
      image: 'ak47.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 13,
        [WeaponQualities.Uncommon]: 14,
        [WeaponQualities.Rare]: 15,
        [WeaponQualities.Epic]: 16,
      },
    },
    {
      name: Weapons.M16,
      category: WeaponCategories.AssaultRifle,
      image: 'm16.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Burst,
      qualities: {
        [WeaponQualities.Common]: 18,
        [WeaponQualities.Uncommon]: 19,
        [WeaponQualities.Rare]: 20,
        [WeaponQualities.Epic]: 21,
      },
    },
    {
      name: Weapons.Scar,
      category: WeaponCategories.AssaultRifle,
      image: 'scar.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 23,
        [WeaponQualities.Uncommon]: 24,
        [WeaponQualities.Rare]: 25,
        [WeaponQualities.Epic]: 26,
      },
    },
    {
      name: Weapons.RanchRifle,
      category: WeaponCategories.AssaultRifle,
      image: 'ranch_rifle.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 153,
        [WeaponQualities.Uncommon]: 154,
        [WeaponQualities.Rare]: 155,
        [WeaponQualities.Epic]: 156,
      },
      notes: {
        'Weakspot Multiplier Bonus': 'x1.1 weakspot multiplier bonus.',
      },
    },

    // Handgun
    {
      name: Weapons.M1911,
      category: WeaponCategories.Handgun,
      image: 'm1911.webp',
      slot: 'secondary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: false,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 29,
        [WeaponQualities.Uncommon]: 30,
        [WeaponQualities.Rare]: 31,
        [WeaponQualities.Epic]: 32,
      },
    },
    {
      name: Weapons.BerettaM9,
      category: WeaponCategories.Handgun,
      image: 'beretta_m9.webp',
      slot: 'secondary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: false,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 34,
        [WeaponQualities.Uncommon]: 35,
        [WeaponQualities.Rare]: 36,
        [WeaponQualities.Epic]: 37,
      },
      notes: {
        'Weakspot Multiplier Bonus': 'x1.1 weakspot multiplier bonus.',
      },
    },
    {
      name: Weapons.BerettaM9Burst,
      category: WeaponCategories.Handgun,
      image: 'beretta_m9.webp',
      slot: 'secondary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: false,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Burst,
      qualities: {
        [WeaponQualities.Common]: 39,
        [WeaponQualities.Uncommon]: 40,
        [WeaponQualities.Rare]: 41,
        [WeaponQualities.Epic]: 42,
      },
      notes: {
        'Weakspot Multiplier Bonus': 'x1.1 weakspot multiplier bonus.',
      },
    },
    {
      name: Weapons.Magnum357,
      category: WeaponCategories.Handgun,
      image: '357_magnum.webp',
      slot: 'secondary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 44,
        [WeaponQualities.Uncommon]: 45,
        [WeaponQualities.Rare]: 46,
        [WeaponQualities.Epic]: 47,
      },
    },
    {
      name: Weapons.Glock23,
      category: WeaponCategories.Handgun,
      image: 'glock_23.webp',
      slot: 'secondary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: false,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 49,
        [WeaponQualities.Uncommon]: 50,
        [WeaponQualities.Rare]: 51,
        [WeaponQualities.Epic]: 52,
      },
    },
    {
      name: Weapons.Glock23Burst,
      category: WeaponCategories.Handgun,
      image: 'glock_23.webp',
      slot: 'secondary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: false,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Burst,
      qualities: {
        [WeaponQualities.Common]: 54,
        [WeaponQualities.Uncommon]: 55,
        [WeaponQualities.Rare]: 56,
        [WeaponQualities.Epic]: 57,
      },
    },
    {
      name: Weapons.DesertEagle,
      category: WeaponCategories.Handgun,
      image: 'desert_eagle.webp',
      slot: 'secondary',
      ammo: 'sniper',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 59,
        [WeaponQualities.Uncommon]: 60,
        [WeaponQualities.Rare]: 61,
        [WeaponQualities.Epic]: 62,
      },
    },
    {
      name: Weapons.Embezzler,
      category: WeaponCategories.Handgun,
      image: 'embezzler.webp',
      slot: 'secondary',
      ammo: 'rifle',
      attachments: {
        barrel: false,
        magazine: false,
        scope: false,
        stock: false,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.LegendaryWeak]: 63,
        [WeaponQualities.Legendary]: 64,
      },
      notes: {
        'Death and Taxes': 'Killing blows generate up to 10 Copper per kill.',
      },
    },

    // LMG
    {
      name: Weapons.M249,
      category: WeaponCategories.LMG,
      image: 'm249.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 67,
        [WeaponQualities.Uncommon]: 68,
        [WeaponQualities.Rare]: 69,
        [WeaponQualities.Epic]: 70,
      },
    },
    {
      name: Weapons.RPK,
      category: WeaponCategories.LMG,
      image: 'rpk.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 72,
        [WeaponQualities.Uncommon]: 73,
        [WeaponQualities.Rare]: 74,
        [WeaponQualities.Epic]: 75,
      },
    },
    {
      name: Weapons.Nemesis,
      category: WeaponCategories.LMG,
      image: 'rpk.webp',
      slot: 'primary',
      ammo: 'rifle',
      attachments: {
        barrel: false,
        magazine: false,
        scope: false,
        stock: false,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.LegendaryWeak]: 76,
        [WeaponQualities.Legendary]: 77,
      },
      notes: {
        'Final Showdown': 'Enemies within 30 meters are drawn to the wielder of this weapon.',
      },
    },

    // Shotgun
    {
      name: Weapons.Express870,
      category: WeaponCategories.Shotgun,
      image: '870_express.webp',
      slot: 'primary',
      ammo: 'shotgun',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Rechamber,
      qualities: {
        [WeaponQualities.Common]: 80,
        [WeaponQualities.Uncommon]: 81,
        [WeaponQualities.Rare]: 82,
        [WeaponQualities.Epic]: 83,
      },
    },
    {
      name: Weapons.AA12,
      category: WeaponCategories.Shotgun,
      image: 'aa12.webp',
      slot: 'primary',
      ammo: 'shotgun',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 85,
        [WeaponQualities.Uncommon]: 86,
        [WeaponQualities.Rare]: 87,
        [WeaponQualities.Epic]: 88,
      },
    },
    {
      name: Weapons.Damnation,
      category: WeaponCategories.Shotgun,
      image: 'aa12.webp',
      slot: 'primary',
      ammo: 'shotgun',
      attachments: {
        barrel: false,
        magazine: false,
        scope: false,
        stock: false,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.LegendaryWeak]: 89,
        [WeaponQualities.Legendary]: 90,
      },
      notes: {
        'Fire and Brimstone': 'Incendiary rounds burn targets for 50 damage per second for 3 seconds. Damnation\'s wielder is immune to Fire Damage.',
      },
    },
    {
      name: Weapons.TheBelgian,
      category: WeaponCategories.Shotgun,
      image: 'the_belgian.webp',
      slot: 'secondary',
      ammo: 'shotgun',
      attachments: {
        barrel: false,
        magazine: false,
        scope: false,
        stock: false,
      },
      rpmFormula: WeaponRpmFormulas.TheBelgian,
      qualities: {
        [WeaponQualities.Common]: 92,
        [WeaponQualities.Uncommon]: 93,
        [WeaponQualities.Rare]: 94,
        [WeaponQualities.Epic]: 95,
      },
    },
    {
      name: Weapons.TAC14,
      category: WeaponCategories.Shotgun,
      image: 'tac14.webp',
      slot: 'primary',
      ammo: 'shotgun',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.TAC14,
      qualities: {
        [WeaponQualities.Common]: 97,
        [WeaponQualities.Uncommon]: 98,
        [WeaponQualities.Rare]: 99,
        [WeaponQualities.Epic]: 100,
      },
    },
    {
      name: Weapons.Super90,
      category: WeaponCategories.Shotgun,
      image: 'super90.webp',
      slot: 'primary',
      ammo: 'shotgun',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 102,
        [WeaponQualities.Uncommon]: 103,
        [WeaponQualities.Rare]: 104,
        [WeaponQualities.Epic]: 105,
      },
    },

    // SMG
    {
      name: Weapons.MP5,
      category: WeaponCategories.SMG,
      image: 'mp5.webp',
      slot: 'primary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 108,
        [WeaponQualities.Uncommon]: 109,
        [WeaponQualities.Rare]: 110,
        [WeaponQualities.Epic]: 111,
      },
    },
    {
      name: Weapons.UZI,
      category: WeaponCategories.SMG,
      image: 'uzi.webp',
      slot: 'primary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 113,
        [WeaponQualities.Uncommon]: 114,
        [WeaponQualities.Rare]: 115,
        [WeaponQualities.Epic]: 116,
      },
    },
    {
      name: Weapons.TEC9,
      category: WeaponCategories.SMG,
      image: 'tec9.webp',
      slot: 'secondary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: false,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 118,
        [WeaponQualities.Uncommon]: 119,
        [WeaponQualities.Rare]: 120,
        [WeaponQualities.Epic]: 121,
      },
    },
    {
      name: Weapons.UMP45,
      category: WeaponCategories.SMG,
      image: 'ump45.webp',
      slot: 'primary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 123,
        [WeaponQualities.Uncommon]: 124,
        [WeaponQualities.Rare]: 125,
        [WeaponQualities.Epic]: 126,
      },
    },
    {
      name: Weapons.Prototype378,
      category: WeaponCategories.SMG,
      image: 'ump45.webp',
      slot: 'primary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: false,
        magazine: false,
        scope: false,
        stock: false,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.LegendaryWeak]: 127,
        [WeaponQualities.Legendary]: 128,
      },
      notes: {
        'ZAP!': 'Significantly slows targets for 1 seconds.',
      },
    },
    {
      name: Weapons.Vector,
      category: WeaponCategories.SMG,
      image: 'vector.webp',
      slot: 'primary',
      ammo: 'pistol_smg',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.Common]: 130,
        [WeaponQualities.Uncommon]: 131,
        [WeaponQualities.Rare]: 132,
        [WeaponQualities.Epic]: 133,
      },
    },

    // Snipers
    {
      name: Weapons.Phoenix350L,
      category: WeaponCategories.Sniper,
      image: 'phoenix_350l.webp',
      slot: 'primary',
      ammo: 'sniper',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Rechamber,
      qualities: {
        [WeaponQualities.Common]: 136,
        [WeaponQualities.Uncommon]: 137,
        [WeaponQualities.Rare]: 138,
        [WeaponQualities.Epic]: 139,
      },
    },
    {
      name: Weapons.BarrettM95,
      category: WeaponCategories.Sniper,
      image: 'barrett_m95.webp',
      slot: 'primary',
      ammo: 'sniper',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Rechamber,
      qualities: {
        [WeaponQualities.Common]: 141,
        [WeaponQualities.Uncommon]: 142,
        [WeaponQualities.Rare]: 143,
        [WeaponQualities.Epic]: 144,
      },
    },
    {
      name: Weapons.M1A,
      category: WeaponCategories.Sniper,
      image: 'm1a.webp',
      slot: 'primary',
      ammo: 'sniper',
      attachments: {
        barrel: true,
        magazine: true,
        scope: true,
        stock: true,
      },
      rpmFormula: WeaponRpmFormulas.Rechamber,
      qualities: {
        [WeaponQualities.Common]: 146,
        [WeaponQualities.Uncommon]: 147,
        [WeaponQualities.Rare]: 148,
        [WeaponQualities.Epic]: 149,
      },
    },
    {
      name: Weapons.Witness,
      category: WeaponCategories.Sniper,
      image: 'witness.webp',
      slot: 'primary',
      ammo: 'sniper',
      attachments: {
        barrel: false,
        magazine: false,
        scope: false,
        stock: false,
      },
      rpmFormula: WeaponRpmFormulas.Default,
      qualities: {
        [WeaponQualities.LegendaryWeak]: 150,
        [WeaponQualities.Legendary]: 151,
      },
      notes: {
        'Sight Unseen': 'Highlights targets and increases damage dealt to them by 20%.',
        'Attachments': 'Always have a 4x scope (does not increase weakspot damage) and suppressor (does not increase damage to unaware enemies) equipped.',
      },
    },
  ],

  Melee: [
    {
      name: Weapons.Bat,
      category: WeaponCategories.Melee,
      image: 'bat.webp',
      slot: 'secondary',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Common]: 5,
        [WeaponQualities.Uncommon]: 6,
        [WeaponQualities.Rare]: 7,
        [WeaponQualities.Epic]: 8,
      },
    },
    {
      name: Weapons.Axe,
      category: WeaponCategories.Melee,
      image: 'fire_axe.webp',
      slot: 'secondary',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Common]: 9,
        [WeaponQualities.Uncommon]: 10,
        [WeaponQualities.Rare]: 11,
        [WeaponQualities.Epic]: 12,
      },
    },
    {
      name: Weapons.Hatchet,
      category: WeaponCategories.Melee,
      image: 'hatchet.webp',
      slot: 'secondary',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Common]: 15,
        [WeaponQualities.Uncommon]: 16,
        [WeaponQualities.Rare]: 17,
        [WeaponQualities.Epic]: 18,
      },
    },
    {
      name: Weapons.Machete,
      category: WeaponCategories.Melee,
      image: 'machete.webp',
      slot: 'secondary',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Common]: 19,
        [WeaponQualities.Uncommon]: 20,
        [WeaponQualities.Rare]: 21,
        [WeaponQualities.Epic]: 22,
      },
    },
    {
      name: Weapons.Tenderizer,
      category: WeaponCategories.Melee,
      image: 'tenderizer.webp',
      slot: 'secondary',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.LegendaryWeak]: 13,
        [WeaponQualities.Legendary]: 14,
      },
      notes: {
        'Mincemeat': 'Dismembers enemies upon impact, and deals 90 damage in a large area of effect.',
      },
    },
    {
      name: Weapons.SkullTotem,
      category: WeaponCategories.Melee,
      image: 'skull_totem.webp',
      slot: 'n/a',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Rare]: 27,
        [WeaponQualities.Epic]: 28,
        [WeaponQualities.Legendary]: 29,
      },
      notes: {
        'Inversed quality': 'Statistics worsen when you increase quality. (not applicable for damage and stumble)',
      },
    },
    {
      name: Weapons.Knife,
      category: WeaponCategories.Melee,
      image: 'knife.webp',
      slot: 'n/a',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Common]: 24,
      },
    },
    {
      name: Weapons.Fist,
      category: WeaponCategories.Melee,
      image: 'fist.png',
      slot: 'n/a',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Common]: 23,
      },
    },
    {
      name: Weapons.BobArm,
      category: WeaponCategories.Melee,
      image: 'bob_arm.png',
      slot: 'n/a',
      rpmFormula: WeaponRpmFormulas.Melee,
      qualities: {
        [WeaponQualities.Common]: 26,
      },
    },
  ],
};